version: "3.8"
services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_DB: recipes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nataly6...
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://db:5432/recipes_db
      - DB_USER=postgres
      - DB_PASSWORD=Nataly6...
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres_data: